/**
 * Default provider configurations extracted from index.html (PROVIDER_PRESETS).
 * All 52 providers from the original application, converted to TypeScript types.
 * Contains built-in, preset, and custom provider definitions.
 */

import { ProviderConfig } from './types';

export const DEFAULT_PROVIDERS: ProviderConfig[] = [
  // ============================================================
  // BUILT-IN PROVIDERS (from index.html)
  // ============================================================
  {
    id: 'builtin-puter-text',
    name: 'Puter.js (optional, no key)',
    type: 'text',
    adapterId: 'puter',
    baseUrl: 'puter.ai.chat',
    authType: 'none',
    priority: 200,
    enabled: true,
    noKeyNeeded: true,
    isPreset: true,
    isBuiltIn: true,
    notes: "Independent infra, no signup — enabled by default (priority 200, so it's only ever tried last, after every keyed provider) so text generation has a genuine zero-setup path. Its hosted models can occasionally hit Puter's own paid-usage paywall and show an \"Upgrade Now\" modal this app can't control — if that happens, add a real provider key in Keys & Providers instead. Disable here if you'd rather text generation fail outright than risk that modal.",
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'builtin-huggingface-text',
    name: 'Hugging Face (built-in text)',
    type: 'text',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'Qwen/Qwen3-32B-Instruct',
    priority: 20,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: true,
    notes: 'PHASE 2 FIX: this used to be a hardcoded step with no adjustable priority, which meant it (and Pollinations) always ran before ANY registry provider regardless of what priority you set there — even a priority-1 OpenAI entry. Now a real registry entry like everything else, so its position in the chain genuinely reflects this priority number.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'builtin-pollinations-text',
    name: 'Pollinations Text (needs free key)',
    type: 'text',
    adapterId: 'pollinations',
    baseUrl: 'https://gen.pollinations.ai',
    authType: 'bearer',
    defaultModel: 'openai',
    priority: 18,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: true,
    notes: "CONFIRMED CHANGE (per Pollinations' own docs, mid-2026): Pollinations no longer offers true no-key client-side generation — publishable (pk_) keys were replaced by a Bring-Your-Own-Pollen OAuth flow, and \"all generation requests require an API key.\" Get a free key at enter.pollinations.ai (a free Pollen allowance is included). This entry is enabled by default but will correctly skip itself with a clear message until a key is set — it's no longer the guaranteed zero-setup option it used to be.",
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'builtin-pollinations-image',
    name: 'Pollinations Flux Image (needs free key)',
    type: 'image',
    adapterId: 'pollinations',
    baseUrl: 'https://gen.pollinations.ai',
    authType: 'bearer',
    defaultModel: 'flux',
    priority: 18,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: true,
    notes: 'Same confirmed change as the text entry — Pollinations now requires a key for all generation, including image. Get a free key at enter.pollinations.ai.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'builtin-huggingface-image',
    name: 'Hugging Face (built-in image)',
    type: 'image',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'black-forest-labs/FLUX.1-dev',
    priority: 20,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: true,
    notes: 'Phase 2 fix: same as builtin-huggingface-text — now a real, priority-adjustable registry entry instead of an unconditionally-first hardcoded step.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'builtin-huggingface-video',
    name: 'Hugging Face (built-in video)',
    type: 'video',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'Wan-AI/Wan2.1-T2V-14B',
    priority: 20,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: true,
    notes: "Phase 2 fix: now a real registry entry. Video support is additionally gated by a live check against Hugging Face's own model registry before any generation attempt.",
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'builtin-huggingface-speech',
    name: 'Hugging Face (built-in speech)',
    type: 'speech',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'hexgrad/Kokoro-82M',
    priority: 25,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: true,
    notes: 'Phase 2 fix: now a real registry entry with an adjustable priority.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'builtin-huggingface-audio',
    name: 'Hugging Face Whisper (built-in transcription)',
    type: 'audio',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'openai/whisper-large-v3',
    priority: 20,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: true,
    notes: 'Phase 2 fix: now a real registry entry with an adjustable priority.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'builtin-huggingface-music',
    name: 'Hugging Face MusicGen (built-in music)',
    type: 'music',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'facebook/musicgen-large',
    priority: 20,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: true,
    notes: "Phase 2 fix: now a real registry entry. Availability is additionally gated by a live check against Hugging Face's own model registry before any generation attempt.",
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'builtin-pollinations-music',
    name: 'Pollinations ElevenMusic (needs free key)',
    type: 'music',
    adapterId: 'pollinations',
    baseUrl: 'https://gen.pollinations.ai',
    authType: 'bearer',
    defaultModel: 'elevenmusic',
    priority: 18,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: true,
    notes: 'Phase 2 fix: now a real registry entry with an adjustable priority, instead of a hardcoded step.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'builtin-puter-tts',
    name: 'Puter.js Speech (optional, no key)',
    type: 'speech',
    adapterId: 'puter',
    baseUrl: 'puter.ai.txt2speech',
    authType: 'none',
    priority: 200,
    enabled: true,
    noKeyNeeded: true,
    isPreset: true,
    isBuiltIn: true,
    notes: 'Real recordable audio file, no key needed — enabled by default (priority 200, tried last) so speech generation has a genuine zero-setup path. Same paywall-modal caveat as the text provider above.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'builtin-browser-speech',
    name: 'Browser Speech Synthesis (built-in, no key)',
    type: 'speech',
    adapterId: 'browser-speech',
    baseUrl: 'speechSynthesis',
    authType: 'none',
    priority: 90,
    enabled: true,
    noKeyNeeded: true,
    isPreset: true,
    isBuiltIn: true,
    notes: 'Last-resort fallback. Can be heard live but NOT saved to a file — browser limitation, not something this app can fix.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'builtin-kenburns-video',
    name: 'Pan/Zoom Still Fallback (built-in, no key)',
    type: 'video',
    adapterId: 'internal-fallback',
    baseUrl: 'internal:ken-burns',
    authType: 'none',
    priority: 95,
    enabled: true,
    noKeyNeeded: true,
    isPreset: true,
    isBuiltIn: true,
    notes: 'Not real AI video — an animated still image, used only when every real video provider fails or isn\'t configured.',
    timeoutMs: 30000,
    retries: 1,
  },

  // ============================================================
  // PRESET PROVIDERS (from index.html)
  // ============================================================
  {
    id: 'preset-groq',
    name: 'Groq',
    type: 'text',
    adapterId: 'groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    authType: 'bearer',
    defaultModel: 'llama-3.3-70b-versatile',
    priority: 11,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'OpenAI-compatible, very fast inference, generous free tier. Get a free key at console.groq.com/keys.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-openrouter-free',
    name: 'OpenRouter (Free Models)',
    type: 'text',
    adapterId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    authType: 'bearer',
    defaultModel: 'meta-llama/llama-3.3-70b-instruct:free',
    priority: 12,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'OpenAI-compatible. One key, many models — use a ":free" suffixed model id to stay on OpenRouter\'s no-cost tier. Browse free models at openrouter.ai/models?max_price=0.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-cerebras',
    name: 'Cerebras',
    type: 'text',
    adapterId: 'openai-compatible',
    baseUrl: 'https://api.cerebras.ai/v1',
    authType: 'bearer',
    defaultModel: 'llama-3.3-70b',
    priority: 13,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'OpenAI-compatible, free tier, extremely fast inference. Get a free key at cloud.cerebras.ai.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-sambanova',
    name: 'SambaNova',
    type: 'text',
    adapterId: 'openai-compatible',
    baseUrl: 'https://api.sambanova.ai/v1',
    authType: 'bearer',
    defaultModel: 'Meta-Llama-3.3-70B-Instruct',
    priority: 14,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'OpenAI-compatible, free tier. Get a free key at cloud.sambanova.ai.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-github-models',
    name: 'GitHub Models',
    type: 'text',
    adapterId: 'openai-compatible',
    baseUrl: 'https://models.inference.ai.azure.com',
    authType: 'bearer',
    defaultModel: 'gpt-4o-mini',
    priority: 15,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'OpenAI-compatible, free with any GitHub account (a GitHub personal access token is used as the API key — no separate signup).',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-cloudflare-text',
    name: 'Cloudflare Workers AI',
    type: 'text',
    adapterId: 'openai-compatible',
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/YOUR_ACCOUNT_ID/ai/v1',
    authType: 'bearer',
    defaultModel: '@cf/meta/llama-3.1-8b-instruct',
    priority: 16,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Replace YOUR_ACCOUNT_ID in the base URL with your Cloudflare account ID. Free tier with a Cloudflare account + API token.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-huggingface-inference',
    name: 'Hugging Face Inference',
    type: 'text',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    priority: 30,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: "Free tier, no credit card. Manually enter the model id — HF doesn't expose a single browsable /models list across all pipeline types. Confirm the exact id is currently live on huggingface.co before relying on it; providers occasionally retire model ids (a previous default here, Qwen/Qwen3-32B-Instruct, stopped resolving).",
    timeoutMs: 300000,
    retries: 3,
  },
  {
    id: 'preset-together',
    name: 'Together AI',
    type: 'text',
    adapterId: 'together',
    baseUrl: 'https://api.together.xyz/v1',
    authType: 'bearer',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    priority: 25,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-deepinfra',
    name: 'DeepInfra',
    type: 'text',
    adapterId: 'deepinfra',
    baseUrl: 'https://api.deepinfra.com/v1/openai',
    authType: 'bearer',
    defaultModel: 'meta-llama/Meta-Llama-3.1-70B-Instruct',
    priority: 25,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-openai',
    name: 'OpenAI',
    type: 'text',
    adapterId: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    authType: 'bearer',
    defaultModel: 'gpt-4o-mini',
    priority: 15,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-anthropic',
    name: 'Anthropic',
    type: 'text',
    adapterId: 'anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    authType: 'header',
    authHeaderName: 'x-api-key',
    defaultModel: 'claude-3-5-haiku-latest',
    priority: 15,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: "Anthropic's API blocks direct browser calls via CORS unless the anthropic-dangerous-direct-browser-access header is sent — added automatically by this adapter.",
    timeoutMs: 30000,
    retries: 1,
    headers: '{"anthropic-version":"2023-06-01"}',
  },
  {
    id: 'preset-gemini',
    name: 'Google Gemini',
    type: 'text',
    adapterId: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    authType: 'query',
    authQueryParam: 'key',
    defaultModel: 'gemini-1.5-flash',
    priority: 15,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-xai',
    name: 'xAI (Grok)',
    type: 'text',
    adapterId: 'openai-compatible',
    baseUrl: 'https://api.x.ai/v1',
    authType: 'bearer',
    defaultModel: 'grok-2-latest',
    priority: 20,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-mistral',
    name: 'Mistral AI',
    type: 'text',
    adapterId: 'openai-compatible',
    baseUrl: 'https://api.mistral.ai/v1',
    authType: 'bearer',
    defaultModel: 'mistral-small-latest',
    priority: 20,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-huggingface-flux',
    name: 'Hugging Face FLUX',
    type: 'image',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'black-forest-labs/FLUX.1-dev',
    priority: 30,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Alternate default: stabilityai/stable-diffusion-xl-base-1.0. Manually enter the model id.',
    timeoutMs: 300000,
    retries: 3,
  },
  {
    id: 'preset-cloudflare-flux',
    name: 'Cloudflare FLUX',
    type: 'image',
    adapterId: 'openai-compatible',
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/YOUR_ACCOUNT_ID/ai/run',
    authType: 'bearer',
    defaultModel: '@cf/black-forest-labs/flux-1-schnell',
    priority: 31,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: "Replace YOUR_ACCOUNT_ID with your Cloudflare account ID. Cloudflare Workers AI's request/response shape differs slightly from plain OpenAI images — if the generic adapter can't parse the response, add a small custom adapter or use the backend proxy.",
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-openrouter-flux',
    name: 'OpenRouter FLUX',
    type: 'image',
    adapterId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    authType: 'bearer',
    defaultModel: 'black-forest-labs/flux-1-schnell:free',
    priority: 32,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: "OpenRouter's free-tier image routing, where available.",
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-fal-ai',
    name: 'fal.ai',
    type: 'image',
    adapterId: 'falai',
    baseUrl: 'https://fal.run',
    authType: 'header',
    authHeaderName: 'Authorization',
    defaultModel: 'fal-ai/flux/schnell',
    priority: 25,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Blocked by CORS from a browser — requires a backend proxy or serverless function to call. Configured here for completeness, but Test Connection will explain this rather than attempt a doomed direct call.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-replicate-image',
    name: 'Replicate',
    type: 'image',
    adapterId: 'replicate',
    baseUrl: 'https://api.replicate.com/v1',
    authType: 'header',
    authHeaderName: 'Authorization',
    defaultModel: 'black-forest-labs/flux-schnell',
    priority: 25,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Blocked by CORS from a browser — requires a backend proxy or serverless function to call.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-stability-ai',
    name: 'Stability AI',
    type: 'image',
    adapterId: 'openai-compatible',
    baseUrl: 'https://api.stability.ai/v2beta',
    authType: 'bearer',
    defaultModel: 'stable-image-core',
    priority: 20,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-huggingface-wan',
    name: 'Hugging Face Wan',
    type: 'video',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'Wan-AI/Wan2.1-T2V-14B',
    priority: 30,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: "CONFIRMED FIX: the model id previously had a fabricated \"-Diffusers\" suffix that isn't a real HF repo, and requests were wrongly routed through hf-inference, which never serves video (confirmed via HF's own docs: video is fal-ai/Replicate/Novita/WaveSpeedAI only). Alternate default: Wan-AI/Wan2.1-T2V-1.3B (smaller/faster). Raw REST for video isn't a publicly stabilized contract per HF's own SDK docs — if this fails consistently, use the backend proxy option, which can call fal.ai's own SDK server-side instead of guessing at the raw shape.",
    timeoutMs: 300000,
    retries: 3,
  },
  {
    id: 'preset-huggingface-ltx',
    name: 'Hugging Face LTX',
    type: 'video',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'Lightricks/LTX-Video',
    priority: 31,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Faster/lighter text-to-video alternative to Wan. Same raw-REST caveat applies.',
    timeoutMs: 300000,
    retries: 3,
  },
  {
    id: 'preset-huggingface-image-to-video',
    name: 'Hugging Face (Image-to-Video)',
    type: 'video',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'Wan-AI/Wan2.2-TI2V-5B',
    priority: 33,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Animates a source image into real video motion. Same raw-REST caveat as text-to-video applies.',
    timeoutMs: 300000,
    retries: 3,
  },
  {
    id: 'preset-cloudflare-video',
    name: 'Cloudflare AI (Video)',
    type: 'video',
    adapterId: 'openai-compatible',
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/YOUR_ACCOUNT_ID/ai/run',
    authType: 'bearer',
    defaultModel: '@cf/lucataco/stable-video-diffusion',
    priority: 32,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: "Replace YOUR_ACCOUNT_ID with your Cloudflare account ID. Availability/model ids on Workers AI change over time — check developers.cloudflare.com/workers-ai/models for the current video model id.",
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-fal-ai-video',
    name: 'fal.ai (Video)',
    type: 'video',
    adapterId: 'falai',
    baseUrl: 'https://fal.run',
    authType: 'header',
    authHeaderName: 'Authorization',
    defaultModel: 'fal-ai/luma-dream-machine',
    priority: 25,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Blocked by CORS from a browser — requires a backend proxy.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-replicate-video',
    name: 'Replicate (Video)',
    type: 'video',
    adapterId: 'replicate',
    baseUrl: 'https://api.replicate.com/v1',
    authType: 'header',
    authHeaderName: 'Authorization',
    defaultModel: 'minimax/video-01',
    priority: 25,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Blocked by CORS from a browser — requires a backend proxy.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-novita-ai',
    name: 'Novita AI',
    type: 'video',
    adapterId: 'openai-compatible',
    baseUrl: 'https://api.novita.ai/v3',
    authType: 'bearer',
    defaultModel: 'default',
    priority: 30,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-pollinations-video',
    name: 'Pollinations Video (fallback only)',
    type: 'video',
    adapterId: 'pollinations',
    baseUrl: 'https://gen.pollinations.ai/video',
    authType: 'bearer',
    defaultModel: 'wan',
    priority: 80,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Paid (Pollen balance required) — kept low-priority as a fallback per the request, since it\'s not free despite needing a Pollinations key.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-groq-whisper',
    name: 'Groq Whisper',
    type: 'audio',
    adapterId: 'groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    authType: 'bearer',
    defaultModel: 'whisper-large-v3-turbo',
    priority: 20,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'OpenAI-compatible /audio/transcriptions endpoint, free tier, very fast.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-whisper-hf',
    name: 'Whisper (Hugging Face)',
    type: 'audio',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'openai/whisper-large-v3',
    priority: 30,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 300000,
    retries: 3,
  },
  {
    id: 'preset-cloudflare-whisper',
    name: 'Cloudflare Whisper',
    type: 'audio',
    adapterId: 'openai-compatible',
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/YOUR_ACCOUNT_ID/ai/run',
    authType: 'bearer',
    defaultModel: '@cf/openai/whisper',
    priority: 31,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Replace YOUR_ACCOUNT_ID with your Cloudflare account ID.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-deepgram',
    name: 'Deepgram',
    type: 'audio',
    adapterId: 'deepgram',
    baseUrl: 'https://api.deepgram.com/v1',
    authType: 'header',
    authHeaderName: 'Authorization',
    defaultModel: 'nova-2',
    priority: 25,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Auth header value should be "Token YOUR_KEY".',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-assemblyai',
    name: 'AssemblyAI',
    type: 'audio',
    adapterId: 'assemblyai',
    baseUrl: 'https://api.assemblyai.com/v2',
    authType: 'header',
    authHeaderName: 'Authorization',
    defaultModel: 'default',
    priority: 25,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-elevenlabs',
    name: 'ElevenLabs',
    type: 'speech',
    adapterId: 'elevenlabs',
    baseUrl: 'https://api.elevenlabs.io/v1',
    authType: 'header',
    authHeaderName: 'xi-api-key',
    defaultModel: 'eleven_multilingual_v2',
    priority: 20,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-kokoro-hf',
    name: 'Kokoro (Hugging Face)',
    type: 'speech',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'hexgrad/Kokoro-82M',
    priority: 35,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 300000,
    retries: 3,
  },
  {
    id: 'preset-piper',
    name: 'Piper (self-hosted)',
    type: 'speech',
    adapterId: 'openai-compatible',
    baseUrl: '',
    authType: 'none',
    defaultModel: '',
    priority: 40,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Piper typically runs locally/self-hosted — set Base URL to your own running instance.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-playht',
    name: 'PlayHT',
    type: 'speech',
    adapterId: 'playht',
    baseUrl: 'https://api.play.ht/api/v2',
    authType: 'header',
    authHeaderName: 'Authorization',
    defaultModel: 'PlayHT2.0',
    priority: 25,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-musicgen-hf',
    name: 'MusicGen (Hugging Face)',
    type: 'music',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'facebook/musicgen-large',
    priority: 20,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 300000,
    retries: 3,
  },
  {
    id: 'preset-stable-audio',
    name: 'Stable Audio',
    type: 'music',
    adapterId: 'openai-compatible',
    baseUrl: 'https://api.stability.ai/v2beta',
    authType: 'bearer',
    defaultModel: 'stable-audio-2',
    priority: 25,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: '',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-local-musicgen',
    name: 'Local MusicGen (self-hosted)',
    type: 'music',
    adapterId: 'openai-compatible',
    baseUrl: '',
    authType: 'none',
    defaultModel: 'musicgen',
    priority: 30,
    enabled: false,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: "Only useful if you're running a local MusicGen server (e.g. via audiocraft or a local inference server) — set Base URL to that instance. Disabled by default since most people don't have one running.",
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-github-models-coding',
    name: 'GitHub Models (Coding)',
    type: 'coding',
    adapterId: 'openai-compatible',
    baseUrl: 'https://models.inference.ai.azure.com',
    authType: 'bearer',
    defaultModel: 'gpt-4o-mini',
    priority: 20,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Same free GitHub Models endpoint as the text category, listed here too since it\'s commonly used for coding assistance.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-openrouter-agents',
    name: 'OpenRouter (Agents)',
    type: 'agents',
    adapterId: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    authType: 'bearer',
    defaultModel: 'meta-llama/llama-3.3-70b-instruct:free',
    priority: 20,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Placeholder entry for agentic/tool-use workflows built on top of OpenRouter\'s free models.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-custom-mcp',
    name: 'Custom MCP Server',
    type: 'mcp',
    adapterId: 'openai-compatible',
    baseUrl: '',
    authType: 'none',
    defaultModel: '',
    priority: 50,
    enabled: false,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Point Base URL at a locally-running MCP-compatible server. This category is registry-only in this build — no built-in MCP client pipeline is wired up yet.',
    timeoutMs: 30000,
    retries: 1,
  },
  {
    id: 'preset-huggingface-research',
    name: 'Hugging Face (Research)',
    type: 'research',
    adapterId: 'huggingface',
    baseUrl: 'https://router.huggingface.co',
    authType: 'bearer',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    priority: 30,
    enabled: true,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Reuses the Hugging Face text pipeline for research/summarization-style prompts.',
    timeoutMs: 300000,
    retries: 3,
  },
  {
    id: 'preset-custom-gamegen',
    name: 'Custom Game-Gen Endpoint',
    type: 'gamegen',
    adapterId: 'openai-compatible',
    baseUrl: '',
    authType: 'none',
    defaultModel: '',
    priority: 50,
    enabled: false,
    noKeyNeeded: false,
    isPreset: true,
    isBuiltIn: false,
    notes: 'Registry-only placeholder for a procedural/game-content generation API — add your own endpoint here.',
    timeoutMs: 30000,
    retries: 1,
  },
];
